# Generated by Django 2.2.7 on 2020-01-27 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0008_stafflog_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos365',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contract_duration', models.IntegerField(choices=[(0, '6 tháng'), (1, '1 năm'), (2, '2 năm'), (3, 'Trọn đời')], default=0)),
                ('contract_start_date', models.DateTimeField(null=True)),
                ('contract_file', models.FileField(null=True, upload_to='pos365s/%Y/%m/%d/')),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('customer_phone', models.CharField(max_length=50, null=True)),
                ('customer_delegate_person', models.CharField(max_length=255, null=True)),
                ('customer_address', models.CharField(max_length=255, null=True)),
                ('point', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos365_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos365s', to='staff.Staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos365_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos365',
                'ordering': ['-created_date'],
                'default_permissions': (),
            },
        ),
    ]
