# Generated by Django 2.1.5 on 2020-03-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos365', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos365',
            name='point',
        ),
    ]
