# Generated by Django 2.2.7 on 2020-05-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_unit', '0001_initial'),
        ('pos365', '0002_remove_pos365_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos365',
            name='contract_product',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pos365',
            name='contract_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pos365',
            name='customer_merchant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pos365',
            name='customer_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos365s', to='administrative_unit.QrProvince'),
        ),
        migrations.AlterField(
            model_name='pos365',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
