# Generated by Django 2.2.7 on 2020-07-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20200318_1006'),
        ('pos365', '0003_auto_20200507_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos365',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('pos365_list_data', 'Can get pos365 list data'), ('pos365_create', 'Can create pos365'), ('pos365_detail', 'Can get pos365 detail'), ('pos365_edit', 'Can edit pos365'), ('pos365_export', 'Can export data pos365'))},
        ),
        migrations.AddField(
            model_name='pos365',
            name='contract_coefficient',
            field=models.IntegerField(default=100, help_text='Hệ số hợp đồng, tỷ lệ từ 0 đến 100'),
        ),
        migrations.AddField(
            model_name='pos365',
            name='contract_team',
            field=models.ForeignKey(help_text='Team - dùng trong TH hợp đồng của cộng tác viên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos365s', to='team.Team'),
        ),
    ]
