# Generated by Django 2.2.7 on 2020-07-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos365', '0004_auto_20200703_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos365',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('pos365_list_data', 'Can get pos365 list data'), ('pos365_create', 'Can create pos365'), ('pos365_detail', 'Can get pos365 detail'), ('pos365_edit', 'Can edit pos365'), ('pos365_export', 'Can export data pos365'), ('pos365_extend_the_duration', 'Có thể gia hạn HĐ'))},
        ),
        migrations.RemoveField(
            model_name='pos365',
            name='contract_product',
        ),
        migrations.RemoveField(
            model_name='pos365',
            name='customer_delegate_person',
        ),
        migrations.RemoveField(
            model_name='pos365',
            name='name',
        ),
        migrations.AddField(
            model_name='pos365',
            name='contract_note',
            field=models.TextField(help_text='Ghi chú', null=True),
        ),
        migrations.AddField(
            model_name='pos365',
            name='contract_product_quantity',
            field=models.IntegerField(default=1, help_text='Số lượng sản phẩm', null=True),
        ),
        migrations.AddField(
            model_name='pos365',
            name='contract_product_series',
            field=models.TextField(help_text='Series thiết bị bán/cho thuê', null=True),
        ),
        migrations.AddField(
            model_name='pos365',
            name='contract_revenue',
            field=models.IntegerField(default=0, help_text='Doanh thu', null=True),
        ),
        migrations.AlterField(
            model_name='pos365',
            name='code',
            field=models.CharField(help_text='Số hợp đồng', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pos365',
            name='contract_url',
            field=models.TextField(help_text='Link phần mềm', null=True),
        ),
    ]
