image: "python:3.6.2"

stages:
#  - test
  - deploy

#test:
#  stage: test
#  script:
#    - echo "Testing stage"
#  only:
#    - master

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch -p ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - ssh root@45.77.246.200
    - ls -la
    - touch longtest.txt
  only:
    - master