image: python:3.6

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cp .env.sample .env
    - sed -i "s/YOUR_TEST_DB_NAME/$TEST_DB_NAME/g" .env
    - sed -i "s/YOUR_TEST_USER/$TEST_USER/g" .env
    - sed -i "s/YOUR_TEST_PASSWORD/$TEST_PASSWORD/g" .env
    - sed -i "s/YOUR_TEST_HOST/$TEST_HOST/g" .env
    - pip install -r requirements-dev.txt
    - pytest
  only:
    - master
  tags:
    - marketing-portal

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh "$SEVER_UNAME"@"SEVER_HOST"
    - cd /home/khdn
    - touch test_gitlabci.txt
  only:
    - master
  tags:
    - marketing-portal
