image: python:3.6

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cp .env.sample .env
    - sed -i 's/YOUR_TEST_DB_NAME/sp_pytest/g' .env
    - sed -i 's/YOUR_TEST_USER/spv2_user/g' .env
    - sed -i 's/YOUR_TEST_PASSWORD/secret123/g' .env
    - sed -i 's/YOUR_TEST_HOST/45.77.246.200/g' .env
    - pip install -r requirements-dev.txt
    - pytest
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $SEVER_UNAME@45.77.246.200 "systemctl stop saleportalv2
      && cd /var/www/sale_portal_v2
      && git pull origin master
      && source .venv/bin/activate
      && pip install -r requirements.txt
      && python manage.py migrate
      && systemctl start saleportalv2"
  only:
    - master
