image: "python:3.6.2"

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Testing stage"
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 400 ~/.ssh
    - cd ~/.ssh
    - ls -la
  script:
    - pwd
    - whoami
  only:
    - master