image: "python:3.6.2"

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Testing stage"
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - echo "$SEVER_IP"
    - echo "$SEVER_UNAME"
  script:
    - pwd
    - whoami
  only:
    - master