image: "python:3.6.2"

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - whoami
    - ls -la
    - pwd
  script:
    - touch test_gitlabct.txt
    - ls -la
  only:
    - master