image: ubuntu

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $SEVER_IP@$SEVER_UNAME "systemctl stop saleportalv2
      && cd /var/www/sale_portal_v2
      && git pull origin master
      && source .venv/bin/activate
      && python manage.py migrate
      && systemctl start saleportalv2"
  only:
    - master
