# Generated by Django 2.1.5 on 2019-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_portal_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
