# Generated by Django 2.1.5 on 2019-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_portal_ingestion', '0002_auto_20190722_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
