# Generated by Django 2.2.7 on 2019-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_report_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='new_using_application',
            field=models.CharField(blank=True, choices=[('iPos', 'iPos'), ('Sapo', 'Sapo'), ('KiotViet', 'KiotViet'), ('POS365', 'POS365'), ('Cukcuk', 'Cukcuk'), ('Ocha', 'Ocha'), ('PM khác', 'PM khác'), ('Chưa sử dụng', 'Chưa sử dụng')], max_length=100, null=True),
        ),
    ]
