# Generated by Django 2.2.7 on 2019-11-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_report_form', '0002_salereport_new_using_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salereport',
            options={'default_permissions': (('sale_report_create', 'Can create sale_report'),), 'ordering': ['-created_date']},
        ),
    ]
