# Generated by Django 2.2.7 on 2019-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_report_form', '0003_auto_20191120_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='data_version',
            field=models.IntegerField(choices=[(1, 'Data synchronize from sale portal version 1'), (2, 'Data create in sale portal version 2')], default=2),
        ),
        migrations.AddField(
            model_name='salereport',
            name='image_inside_v2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salereport',
            name='image_outside_v2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salereport',
            name='image_store_cashier_v2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='customer_care_cashier_reward',
            field=models.IntegerField(blank=True, choices=[(0, 'Không'), (1, 'Có')], default=0, help_text='Noi dung Cham soc - KQ cham soc - Ky HD thuong thu ngan khong?', null=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='customer_care_transaction',
            field=models.IntegerField(blank=True, default=0, help_text='Noi dung Cham soc - KQ cham soc - SLGD phat sinh trong thoi gian cham soc', null=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='implement_career_guideline',
            field=models.TextField(help_text='Noi dung Trien khai - Da huong dan nghiep vu cho ai', null=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='implement_merchant_view',
            field=models.TextField(help_text='Noi dung Trien khai - Merchant view cho Terminal gom nhung gi', null=True),
        ),
    ]
