# Generated by Django 2.2.7 on 2019-12-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_report_form', '0004_auto_20191219_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='cessation_of_business_image_v2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
