# Generated by Django 2.2.7 on 2019-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_report_form', '0005_salereport_cessation_of_business_image_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='posm_v2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
