# Generated by Django 2.2.7 on 2020-02-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_report_form', '0006_salereport_posm_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salereport',
            options={'default_permissions': (), 'ordering': ['-created_date']},
        ),
    ]
