# Generated by Django 2.2.7 on 2019-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrStaff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('staff_code', models.TextField(null=True)),
                ('nick_name', models.TextField(null=True)),
                ('full_name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('mobile', models.TextField(null=True)),
                ('department_code', models.TextField(null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('department_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'qr_staff',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(help_text='Equivalent with qr_staff.staff_code', max_length=200, null=True)),
                ('nick_name', models.CharField(help_text='Equivalent with qr_staff.nick_name', max_length=200, null=True)),
                ('full_name', models.CharField(help_text='Equivalent with qr_staff.full_name', max_length=200, null=True)),
                ('email', models.CharField(help_text='Equivalent with qr_staff.email', max_length=200, null=True)),
                ('mobile', models.CharField(help_text='Equivalent with qr_staff.mobile', max_length=200, null=True)),
                ('department_code', models.CharField(help_text='Equivalent with qr_staff.department_code', max_length=200, null=True)),
                ('status', models.IntegerField(default=1, help_text='Equivalent with qr_staff.status')),
                ('department_id', models.IntegerField(help_text='Equivalent with qr_staff.department_id', null=True)),
                ('created_date', models.DateTimeField(help_text='Equivalent with qr_staff.created_date', null=True)),
                ('modify_date', models.DateTimeField(help_text='Equivalent with qr_staff.modify_date', null=True)),
            ],
            options={
                'db_table': 'staff',
                'default_permissions': (),
            },
        ),
    ]
