# Generated by Django 2.2.7 on 2019-11-07 16:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('new_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('type', models.IntegerField(choices=[(0, 'New row in qr_terminal table'), (1, 'Deleted from qr_terminal table'), (2, 'Updated from qr_terminal table')])),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'staff_log',
                'default_permissions': (),
            },
        ),
    ]
