# Generated by Django 2.2.7 on 2019-12-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20191113_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(help_text='Equivalent with qr_staff.email', max_length=200, null=True, unique=True),
        ),
    ]
