# Generated by Django 2.2.7 on 2019-12-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20191203_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'default_permissions': (), 'ordering': ['-created_date']},
        ),
    ]
