# Generated by Django 2.2.7 on 2019-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20191210_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafflog',
            name='role_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafflog',
            name='team_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stafflog',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stafflog',
            name='type',
            field=models.IntegerField(choices=[(0, 'New row in qr_terminal table'), (1, 'Deleted from qr_terminal table'), (2, 'Updated from qr_terminal table'), (3, 'Staff join a team'), (4, 'Staff out a team'), (5, 'Staff update role')]),
        ),
    ]
