# Generated by Django 2.2.7 on 2019-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20191210_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTeamLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('team_code', models.CharField(max_length=20, null=True)),
                ('type', models.IntegerField(choices=[(0, 'JOIN_TEAM'), (1, 'OUT_TEAM'), (2, 'UPDATE_ROLE')], null=True)),
                ('role', models.IntegerField(choices=[(0, 'TEAM_STAFF'), (1, 'TEAM_MANAGEMENT')], null=True)),
                ('description', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_team_log',
                'default_permissions': (),
            },
        ),
    ]
