# Generated by Django 2.2.7 on 2019-12-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20191217_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('staff_list_data', 'Can get staff list data'), ('staff_detail', 'Can get staff detail'), ('staff_edit', 'Can edit staff'), ('staff_import', 'Can import data staff'))},
        ),
    ]
