# Generated by Django 2.2.7 on 2019-12-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staffteamlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'default_permissions': (('staff_list_data', 'Can get staff list data'), ('staff_list_search', 'Can get staff list search'), ('staff_detail', 'Can get staff detail'), ('staff_edit', 'Can edit staff'), ('staff_import', 'Can import data staff')), 'ordering': ['-created_date']},
        ),
    ]
