# Generated by Django 2.2.7 on 2019-12-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0007_auto_20191218_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_log_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
