# Generated by Django 2.2.7 on 2020-02-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20200213_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafflog',
            old_name='role_id',
            new_name='role',
        ),
    ]
