# Generated by Django 2.2.7 on 2020-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20200213_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='target_kpi_pos365',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='target_kpi_s73',
            field=models.IntegerField(null=True),
        ),
    ]
