# Generated by Django 2.2.7 on 2019-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=20, null=True)),
                ('district_code', models.CharField(max_length=20, null=True)),
                ('district_name', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'qr_district',
                'ordering': ('province_code', 'district_code'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QrProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=20, null=True)),
                ('province_name', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('brand_name', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'qr_province',
                'ordering': ['province_code'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QrWards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=20, null=True)),
                ('district_code', models.CharField(max_length=20, null=True)),
                ('wards_code', models.CharField(max_length=200, null=True)),
                ('wards_name', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'qr_wards',
                'ordering': ('province_code', 'district_code', 'wards_code'),
                'default_permissions': (),
            },
        ),
    ]
