# Generated by Django 2.2.7 on 2020-03-24 15:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('type', models.CharField(db_column='type', db_index=True, max_length=50)),
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('province_code', models.CharField(blank=True, db_column='province_code', max_length=50, null=True)),
                ('district_code', models.CharField(blank=True, db_column='district_code', max_length=150, null=True)),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField(db_column='geojson')),
            ],
            options={
                'db_table': 'geodata',
                'permissions': (('map_geojson', 'Can get map background'),),
                'default_permissions': (),
            },
        ),
    ]
