# Generated by Django 2.2.7 on 2019-11-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('note', models.TextField(null=True)),
                ('icon', models.TextField(null=True)),
            ],
            options={
                'db_table': 'qr_status',
                'default_permissions': (),
            },
        ),
    ]
