# Generated by Django 2.2.7 on 2019-11-06 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20191106_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('new_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('type', models.IntegerField(choices=[(0, 'New row in qr_merchant table'), (1, 'Deleted in qr_merchant table'), (2, 'Change in field status'), (3, 'Change in field merchant_address'), (4, 'Change in field merchant_name'), (5, 'Change in field merchant_code'), (6, 'Change in field merchant_brand'), (7, 'Change in field merchant_type_id'), (8, 'Change in field staff')])),
            ],
            options={
                'db_table': 'merchant_log',
                'default_permissions': (),
            },
        ),
    ]
