# Generated by Django 2.2.7 on 2019-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_merchantlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantlog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantlog',
            name='merchant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
