# Generated by Django 2.2.7 on 2019-12-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_auto_20191106_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'default_permissions': (), 'ordering': ['-created_date']},
        ),
    ]
