# Generated by Django 2.2.7 on 2020-02-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20191218_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('merchant_list_data', 'Can get merchant list data'), ('merchant_detail', 'Can get merchant detail'), ('merchant_export', 'Can export data merchant'))},
        ),
    ]
