# Generated by Django 2.2.7 on 2020-02-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_auto_20200224_1738'),
        ('merchant', '0007_auto_20200225_0957'),
    ]

    operations = [
    ]
