# Generated by Django 2.2.7 on 2020-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_promotion_form', '0003_auto_20191219_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepromotion',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salepromotion',
            name='sub_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
