# Generated by Django 2.2.7 on 2020-02-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_promotion_form', '0004_auto_20200206_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salepromotion',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (('sale_promotion_list_data', 'Can get sale_promotion list data'), ('sale_promotion_detail', 'Can get sale_promotion detail'), ('sale_promotion_import', 'Can import sale_promotion'), ('sale_promotion_edit', 'Can edit sale_promotion'), ('sale_promotion_export', 'Can export data sale_promotion'), ('sale_promotion_reset_data', 'Can reset data sale_promotion'))},
        ),
        migrations.AlterModelOptions(
            name='salepromotiontitle',
            options={'default_permissions': (), 'permissions': (('promotion_title_list_data', 'Can get promotion_title list data'),)},
        ),
    ]
