# Generated by Django 2.2.7 on 2020-01-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0006_auto_20191218_1525'),
        ('staff', '0008_stafflog_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20200120_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Staff chăm sóc Shop'), (1, 'Staff chuỗi chăm sóc Shop'), (2, 'Staff chăm sóc Merchant')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cares_created', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cares', to='merchant.Merchant')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cares', to='shop.Shop')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cares', to='staff.Staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cares_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_care',
                'ordering': ('-created_date',),
                'default_permissions': (),
                'unique_together': {('staff', 'shop', 'type'), ('staff', 'merchant', 'type')},
            },
        ),
    ]
