# Generated by Django 2.2.7 on 2020-02-10 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20191218_1525'),
        ('staff', '0008_stafflog_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20200120_1714'),
        ('staff_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffcare',
            options={'default_permissions': ()},
        ),
        migrations.AlterUniqueTogether(
            name='staffcare',
            unique_together={('merchant', 'type'), ('shop', 'type')},
        ),
        migrations.CreateModel(
            name='StaffCareLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Staff chăm sóc Shop'), (1, 'Staff chuỗi chăm sóc Shop'), (2, 'Staff chăm sóc Merchant')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_care_logs_created', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_care_logs', to='merchant.Merchant')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_care_logs', to='shop.Shop')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_care_logs', to='staff.Staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_care_logs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_care_log',
                'ordering': ('-created_date',),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='staffcare',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='staffcare',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='staffcare',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='staffcare',
            name='updated_date',
        ),
    ]
