# Generated by Django 2.2.7 on 2020-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_care', '0002_auto_20200210_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcarelog',
            name='is_caring',
            field=models.BooleanField(default=False),
        ),
    ]
