# Generated by Django 2.2.7 on 2020-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_care', '0004_staffcareimportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcareimportlog',
            name='type',
            field=models.IntegerField(choices=[(0, 'Staff chăm sóc Shop'), (1, 'Staff chuỗi chăm sóc Shop'), (2, 'Staff chăm sóc Merchant')], default=0),
        ),
    ]
