# Generated by Django 2.2.7 on 2019-11-13 14:36

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrative_unit', '0001_initial'),
        ('staff', '0003_auto_20191113_0921'),
        ('merchant', '0004_auto_20191106_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('new_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('type', models.IntegerField(choices=[(0, 'Created new'), (1, 'Do not use because do not delete shop'), (2, 'Change staff'), (3, 'Change take care status'), (4, 'Change activate type'), (5, 'Other field updated')])),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_log_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_log',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('take_care_status', models.IntegerField(choices=[(0, 'NOT TAKE CARE'), (1, 'TAKE CARE'), (2, 'OTHER - SHOP CREATED IN TODAY')], default=2)),
                ('street', models.CharField(max_length=200, null=True)),
                ('activated', models.IntegerField(choices=[(0, 'DISABLE'), (1, 'ACTIVATE')], default=1)),
                ('inactivated_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_unit.QrDistrict')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.Merchant')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_unit.QrProvince')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops_updated', to=settings.AUTH_USER_MODEL)),
                ('wards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_unit.QrWards')),
            ],
            options={
                'db_table': 'shop',
                'ordering': ('-created_date',),
                'default_permissions': (),
            },
        ),
    ]
