# Generated by Django 2.2.7 on 2019-11-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='administrative_unit.QrDistrict'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='administrative_unit.QrProvince'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='wards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='administrative_unit.QrWards'),
        ),
    ]
