# Generated by Django 2.2.7 on 2019-11-25 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20191113_0921'),
        ('shop', '0002_auto_20191113_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='staff_of_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_chains', to='staff.Staff'),
        ),
    ]
