# Generated by Django 2.2.7 on 2019-11-26 17:01

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_staff_of_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
