# Generated by Django 2.2.7 on 2019-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='geo_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='geo_generate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
