# Generated by Django 2.2.7 on 2019-11-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191129_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='geo_check',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='geo_generate',
        ),
    ]
