# Generated by Django 2.2.7 on 2020-01-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191218_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='staff_of_chain',
        ),
    ]
