# Generated by Django 2.2.7 on 2020-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200312_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='take_care_status',
            field=models.IntegerField(choices=[(0, 'NOT TAKE CARE'), (1, 'TAKE CARE'), (2, 'CARE_OK')], default=0),
        ),
    ]
