# Generated by Django 2.2.7 on 2020-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200316_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFullData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('street', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('activated', models.IntegerField(null=True)),
                ('take_care_status', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(blank=True, help_text='Ngay tao shop', null=True)),
                ('merchant_id', models.IntegerField(null=True)),
                ('merchant_brand', models.TextField(null=True)),
                ('merchant_code', models.TextField(null=True)),
                ('province_id', models.IntegerField(null=True)),
                ('province_name', models.TextField(null=True)),
                ('district_id', models.IntegerField(null=True)),
                ('district_name', models.TextField(null=True)),
                ('wards_id', models.IntegerField(null=True)),
                ('wards_name', models.TextField(null=True)),
                ('staff_id', models.IntegerField(null=True)),
                ('staff_email', models.TextField(null=True)),
                ('team_id', models.IntegerField(null=True)),
                ('team_name', models.TextField(null=True)),
                ('count_terminals', models.IntegerField(null=True)),
                ('report_date', models.DateField(blank=True, help_text='Ngay bao cao', null=True)),
                ('number_of_tran', models.IntegerField(null=True)),
                ('number_of_tran_w_1_7', models.IntegerField(null=True)),
                ('number_of_tran_w_8_14', models.IntegerField(null=True)),
                ('number_of_tran_w_15_21', models.IntegerField(null=True)),
                ('number_of_tran_w_22_end', models.IntegerField(null=True)),
                ('voucher_code_list', models.TextField(null=True)),
            ],
            options={
                'db_table': 'shop_full_data',
                'managed': False,
            },
        ),
    ]
