# Generated by Django 2.2.7 on 2020-03-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_create_shop_full_data_materialized_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='geo_check',
            field=models.IntegerField(choices=[(0, 'UNCHECK'), (1, 'CHECKED_IN_SHOP_WARD'), (-1, 'CHECKED_NOT_IN_SHOP_WARD')], default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='geo_generate',
            field=models.IntegerField(choices=[(0, 'OTHER'), (1, 'GENERATE_SUCCESS_FROM_GOOGLE_API'), (-1, 'GENERATE_FAILED_FROM_GOOGLE_API')], default=0),
        ),
    ]
