# Generated by Django 2.2.7 on 2020-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200327_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='geo_check',
            field=models.IntegerField(choices=[(0, 'UNCHECK'), (1, 'CHECKED_IN_SHOP_WARD'), (-1, 'CHECKED_NOT_IN_SHOP_WARD'), (-2, 'NOT_FOUND_WARD')], default=0),
        ),
    ]
