# Generated by Django 2.2.7 on 2019-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronjobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'PROCESSING'), (1, 'DONE'), (2, 'ERROR')], default=0)),
                ('description', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cronjob_log',
                'ordering': ['-created_date'],
                'default_permissions': (),
            },
        ),
    ]
