# Generated by Django 2.2.7 on 2019-12-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjoblog',
            options={'default_permissions': (('cronjob_log_list_data', 'Can get cronjob_log list data'),), 'ordering': ['-created_date']},
        ),
    ]
