# Generated by Django 2.2.7 on 2020-02-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_auto_20200214_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjoblog',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('cronjob_list_log', 'Can get list cronjob log'), ('cronjob_list_name', 'Can get area cronjob name'), ('cronjob_run_manual', 'Can run cronjob'))},
        ),
    ]
