# Generated by Django 2.2.7 on 2019-11-29 10:22

from django.db import migrations
import sale_portal.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', sale_portal.user.models.CustomUserManager()),
            ],
        ),
    ]
