# Generated by Django 2.2.7 on 2020-01-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'default_permissions': (), 'ordering': ['name']},
        ),
    ]
