# Generated by Django 2.2.7 on 2020-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200120_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sale_admin',
            field=models.BooleanField(default=False),
        ),
    ]
