# Generated by Django 2.2.7 on 2020-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_sale_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager_outside_vnpay',
            field=models.BooleanField(default=False, help_text='Sale from tripi, teko'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_area_manager',
            field=models.BooleanField(default=False, help_text='Is sale manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_sale_admin',
            field=models.BooleanField(default=False, help_text='Is sale admin'),
        ),
    ]
