from django.db import models


class ShopCube(models.Model):
    shop_id = models.IntegerField(null=False, default=0)
    report_date = models.DateField(null=True, blank=True)
    merchant_code = models.TextField(blank=True, null=True)
    shop_province_code = models.TextField(blank=True, null=True)
    shop_province_name = models.TextField(blank=True, null=True)
    shop_district_code = models.TextField(blank=True, null=True)
    shop_district_name = models.TextField(blank=True, null=True)
    shop_ward_code = models.TextField(blank=True, null=True)
    shop_ward_name = models.TextField(blank=True, null=True)
    shop_area = models.TextField(blank=True, null=True)
    shop_address = models.TextField(blank=True, null=True)
    department_name = models.TextField(blank=True, null=True)
    sale_name = models.TextField(blank=True, null=True)
    sale_email = models.TextField(blank=True, null=True)
    status = models.TextField(blank=True, null=True)
    merchant_brand = models.TextField(blank=True, null=True)
    merchant_group_bussiness_type = models.TextField(blank=True, null=True)
    number_of_tran = models.BigIntegerField(blank=True, null=True)
    value_of_tran = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer = models.BigIntegerField(blank=True, null=True)
    number_of_customer = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer = models.BigIntegerField(blank=True, null=True)
    number_of_tran_7d = models.BigIntegerField(blank=True, null=True)
    value_of_tran_7d = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_7d = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_7d = models.BigIntegerField(blank=True, null=True)
    number_of_customer_7d = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_7d = models.BigIntegerField(blank=True, null=True)
    number_of_tran_30d = models.BigIntegerField(blank=True, null=True)
    value_of_tran_30d = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_30d = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_30d = models.BigIntegerField(blank=True, null=True)
    number_of_customer_30d = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_30d = models.BigIntegerField(blank=True, null=True)
    number_of_tran_acm = models.BigIntegerField(blank=True, null=True)
    value_of_tran_acm = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_acm = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_acm = models.BigIntegerField(blank=True, null=True)
    number_of_customer_acm = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_acm = models.BigIntegerField(blank=True, null=True)
    number_of_tran_w_1_7 = models.BigIntegerField(blank=True, null=True)
    value_of_tran_w_1_7 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_w_1_7 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_w_1_7 = models.BigIntegerField(blank=True, null=True)
    number_of_customer_w_1_7 = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_w_1_7 = models.BigIntegerField(blank=True, null=True)
    number_of_tran_w_8_14 = models.BigIntegerField(blank=True, null=True)
    value_of_tran_w_8_14 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_w_8_14 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_w_8_14 = models.BigIntegerField(blank=True, null=True)
    number_of_customer_w_8_14 = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_w_8_14 = models.BigIntegerField(blank=True, null=True)
    number_of_tran_w_15_21 = models.BigIntegerField(blank=True, null=True)
    value_of_tran_w_15_21 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_w_15_21 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_w_15_21 = models.BigIntegerField(blank=True, null=True)
    number_of_customer_w_15_21 = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_w_15_21 = models.BigIntegerField(blank=True, null=True)
    number_of_tran_w_22_end = models.BigIntegerField(blank=True, null=True)
    value_of_tran_w_22_end = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_w_22_end = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_w_22_end = models.BigIntegerField(blank=True, null=True)
    number_of_customer_w_22_end = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_w_22_end = models.BigIntegerField(blank=True, null=True)
    number_of_tran_last_m_w_1_7 = models.BigIntegerField(blank=True, null=True)
    value_of_tran_last_m_w_1_7 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_last_m_w_1_7 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_last_m_w_1_7 = models.BigIntegerField(blank=True, null=True)
    number_of_customer_last_m_w_1_7 = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_last_m_w_1_7 = models.BigIntegerField(blank=True, null=True)
    number_of_tran_last_m_w_8_14 = models.BigIntegerField(blank=True, null=True)
    value_of_tran_last_m_w_8_14 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_last_m_w_8_14 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_last_m_w_8_14 = models.BigIntegerField(blank=True, null=True)
    number_of_customer_last_m_w_8_14 = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_last_m_w_8_14 = models.BigIntegerField(blank=True, null=True)
    number_of_tran_last_m_w_15_21 = models.BigIntegerField(blank=True, null=True)
    value_of_tran_last_m_w_15_21 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_last_m_w_15_21 = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_last_m_w_15_21 = models.BigIntegerField(blank=True, null=True)
    number_of_customer_last_m_w_15_21 = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_last_m_w_15_21 = models.BigIntegerField(blank=True, null=True)
    number_of_tran_last_m_w_22_end = models.BigIntegerField(blank=True, null=True)
    value_of_tran_last_m_w_22_end = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    promotion_value_last_m_w_22_end = models.DecimalField(blank=True, null=True, max_digits=38, decimal_places=10)
    number_of_new_customer_last_m_w_22_end = models.BigIntegerField(blank=True, null=True)
    number_of_customer_last_m_w_22_end = models.BigIntegerField(blank=True, null=True)
    number_of_un_exp_customer_last_m_w_22_end = models.BigIntegerField(blank=True, null=True)
    _created_date = models.DateTimeField(blank=True, null=True)
    _updated_date = models.DateTimeField(blank=True, null=True)
    point_last_m = models.IntegerField(blank=True, null=True)
    point_last_m_w_1_7 = models.IntegerField(blank=True, null=True)
    point_last_m_w_8_14 = models.IntegerField(blank=True, null=True)
    point_last_m_w_15_21 = models.IntegerField(blank=True, null=True)
    point_last_m_w_22_end = models.IntegerField(blank=True, null=True)
    point_w_1_7 = models.IntegerField(blank=True, null=True)
    point_w_8_14 = models.IntegerField(blank=True, null=True)
    point_w_15_21 = models.IntegerField(blank=True, null=True)
    point_w_22_end = models.IntegerField(blank=True, null=True)
    bonus_point_this_m = models.IntegerField(blank=True, null=True)
    voucher_code_list = models.TextField(blank=True, null=True)
    current_shop_class = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'shop_cube'
        default_permissions = ()

    def __str__(self):
        return str(self.shop_id)
