# Generated by Django 2.2.7 on 2020-07-07 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Sale email', max_length=200, null=True)),
                ('kpi_target', models.IntegerField(default=0, help_text='Target KPI của sale - hệ thống đọc từ google sheet')),
                ('kpi_point_lcc', models.IntegerField(default=0, help_text='Point triển khai LCC - hệ thống đọc từ google sheet')),
                ('kpi_point_other', models.IntegerField(default=0, help_text='Point khác - hệ thống đọc từ google sheet')),
                ('month', models.IntegerField(default=1, help_text='Tháng KPI có hiệu lực', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(default=2020, help_text='Năm KPI có hiệu lực', validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(3000)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kpi',
                'ordering': ['-created_date'],
                'permissions': (('get_data_kpi_yourself', 'Can get data kpi of yourself'), ('get_data_kpi_team', 'Can get data kpi of all member of team')),
                'default_permissions': (),
                'unique_together': {('email', 'month', 'year')},
            },
        ),
    ]
