# Generated by Django 2.2.7 on 2020-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('provinces', models.TextField()),
            ],
            options={
                'db_table': 'area',
                'ordering': ['code'],
                'default_permissions': (),
            },
        ),
    ]
