# Generated by Django 2.2.7 on 2020-02-26 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_auto_20200211_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='proportion_kpi_s73',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
