# Generated by Django 2.2.7 on 2020-02-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangepointpos365',
            options={'default_permissions': (), 'permissions': (('list_exchange_point_pos365_config', 'Can get exchange point pos365 config list '),)},
        ),
    ]
