# Generated by Django 2.2.7 on 2020-02-28 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_kpi', '0002_auto_20200214_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepointpos365',
            name='point',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
