# Generated by Django 2.2.7 on 2020-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_kpi', '0003_auto_20200228_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepointpos365',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
