# Generated by Django 2.2.7 on 2020-02-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cube', '0002_auto_20200216_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcube',
            name='number_of_tran',
            field=models.IntegerField(default=0, help_text='SLGD hom qua'),
        ),
        migrations.AlterField(
            model_name='shopcube',
            name='number_of_tran_w_15_21',
            field=models.IntegerField(default=0, help_text='SLGD ky 3'),
        ),
        migrations.AlterField(
            model_name='shopcube',
            name='number_of_tran_w_1_7',
            field=models.IntegerField(default=0, help_text='SLGD ky 1'),
        ),
        migrations.AlterField(
            model_name='shopcube',
            name='number_of_tran_w_22_end',
            field=models.IntegerField(default=0, help_text='SLGD ky 4'),
        ),
        migrations.AlterField(
            model_name='shopcube',
            name='number_of_tran_w_8_14',
            field=models.IntegerField(default=0, help_text='SLGD ky 2'),
        ),
    ]
