# Generated by Django 2.2.7 on 2020-02-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cube', '0003_auto_20200219_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcube',
            name='voucher_code_list',
            field=models.TextField(blank=True, help_text='Danh sach cac ma voucher dang ap dung', null=True),
        ),
    ]
