# Generated by Django 2.2.7 on 2020-03-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cube', '0004_shopcube_voucher_code_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcube',
            name='rank',
            field=models.IntegerField(default=0, help_text='Thu tu cham soc cac shop'),
        ),
        migrations.AddField(
            model_name='shopcube',
            name='to_do',
            field=models.IntegerField(default=0, help_text='Shop co to_do = 1 la shop can cham soc'),
        ),
    ]
