# Generated by Django 2.2.7 on 2020-06-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cube', '0005_auto_20200311_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcube',
            name='number_of_tran_acm',
            field=models.IntegerField(default=0, help_text='SLGD tu dau thang'),
        ),
        migrations.AddField(
            model_name='shopcube',
            name='number_of_tran_last_m',
            field=models.IntegerField(default=0, help_text='SLGD thang truoc'),
        ),
    ]
