# Generated by Django 2.2.7 on 2019-11-07 10:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('new_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('type', models.IntegerField(choices=[(0, 'New row in qr_terminal table'), (1, 'Deleted in qr_terminal table'), (2, 'Change in field status'), (3, 'Change in field terminal_address'), (4, 'Change in field terminal_name'), (5, 'Change in field register_qr'), (6, 'Change in field register_vnpayment'), (7, 'Change in field wards_code'), (8, 'Change in field business_address'), (9, 'Change in field shop')])),
                ('terminal_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'terminal_log',
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='terminal',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Equivalent with qr_terminal.merchant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='merchant.Merchant'),
        ),
    ]
