# Generated by Django 2.2.7 on 2019-12-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_auto_20191205_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('terminal_list_data', 'Can get terminal list data'), ('terminal_detail', 'Can get terminal detail'), ('terminal_edit', 'Can edit terminal'), ('terminal_export', 'Can export data terminal'))},
        ),
    ]
