# Generated by Django 2.2.7 on 2019-12-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0005_auto_20191218_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminallog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_log_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
