# Generated by Django 2.2.7 on 2020-02-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_terminallog_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('terminal_list_data', 'Can get terminal list data'), ('terminal_detail', 'Can get terminal detail'), ('terminal_edit', 'Can edit terminal'), ('terminal_export', 'Can export data terminal'), ('dashboard_terminal_count', 'Can get terminal data for dashboard'))},
        ),
    ]
