# Generated by Django 2.2.7 on 2019-12-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.IntegerField(choices=[(0, 'Team Sale'), (1, 'Team Chuỗi'), (2, 'Team Trực Tiếp')], default=0),
        ),
    ]
