# Generated by Django 2.2.7 on 2019-12-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'default_permissions': (), 'ordering': ['-created_date']},
        ),
    ]
