# Generated by Django 2.2.7 on 2019-12-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191213_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'default_permissions': (), 'ordering': ['-created_date'], 'permissions': (('team_list_data', 'Can get team list data'), ('team_list_search', 'Can get team list search'), ('team_detail', 'Can get team detail'), ('team_create', 'Can create team'), ('team_edit', 'Can edit team'), ('team_delete', 'Can delete team'), ('team_import', 'Can import data team'))},
        ),
    ]
