# Generated by Django 2.2.7 on 2020-01-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('team', '0005_auto_20191219_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='area.Area'),
        ),
    ]
